name: Discord Notif

on:
  push:
    branches: [ main ] # Replace main with your branch name.

jobs:
  Notify:
    runs-on: ubuntu-latest
    name: Send Notification
    steps:
      - name: Send Notification
        uses: Retr0-01/better-discord-notification@main
        with:
          webhook-url: 'https://discord.com/api/webhooks/682639730105647124/7KTSYM2rTre2vr94qG0WN0jgRhiZdExKvfb_w31-F3rFfbhAfo6YkeZpGP0fzAVwaE31'
          embed-color: '9498256'
          footer-icon: 'https://cdn.discordapp.com/emojis/739680612213981265.gif'
          ignore-hidden: 'true'
