name: Discord Notif

on:
  push:
    branches: [ master ] # Replace main with your branch name.

jobs:
  Notify:
    runs-on: ubuntu-latest
    name: Send Notification
    steps:
      - name: Set git core.longpaths flag
        run: sudo git config --system core.longpaths true
      - name: Send Notification
        uses: level-share-square/supermario127@master
        with:
          webhook-url: ${{ secrets.WEBHOOK_LINK }}
          embed-color: '9498256'
          footer-icon: 'https://cdn.discordapp.com/emojis/739680612213981265.gif'
          ignore-hidden: 'true'
